kind: Service
apiVersion: v1
metadata:
  name: train-schedule-service
  namespace: train-prod
spec:
  type: ClusterIP
  selector:
    app: train-schedule
  ports:
  - protocol: TCP
    port: 8080
    

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: train-schedule-deployment
  namespace: train-prod
  labels:
    app: train-schedule
spec:
  replicas: 2
  selector:
    matchLabels:
      app: train-schedule
  template:
    metadata:
      labels:
        app: train-schedule
    spec:
      containers:
      - name: train-schedule
        image: 517716713836.dkr.ecr.eu-central-1.amazonaws.com/groca/train:latest
        imagePullPolicy: "Always"
        ports:
        - containerPort: 8080
